services:
  python:
    image: docker.io/python:3.11-slim-bullseye
    volumes:
      - ./:/app
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        pip install -r requirements.txt
        python3 main.py
